
{{- $secureSign := .Values.trustedArtifactSigner.secureSign -}}
{{- if $secureSign.enabled }}
  {{- $tasUsername := "trusted-artifact-signer" }}
  {{- $tasEmail := printf "%s@%s" $tasUsername .Values.trustedArtifactSigner.ingressDomain }}
---
apiVersion: rhtas.redhat.com/v1alpha1
kind: Securesign
metadata:
  namespace: {{ $secureSign.namespace }}
  name: {{ $secureSign.name }}
spec:
  fulcio:
    externalAccess:
      enabled: true
    certificate:
      commonName: {{ $secureSign.fulcio.certificate.commonName }}
      organizationEmail:  {{ $tasEmail }}
      organizationName: {{ $secureSign.fulcio.certificate.organizationName }}
    config:
      OIDCIssuers:
        '{{ $secureSign.fulcio.oidc.issuerURL }}':
          IssuerURL: "{{ $secureSign.fulcio.oidc.issuerURL }}"
          ClientID: {{ $tasEmail }}
          Type: email
  rekor:
    externalAccess:
      enabled: true
    rekorSearchUI:
      enabled: true
    signer:
      kms: secret
  trillian:
    database:
      create: true
  tuf:
    externalAccess:
      enabled: true
    port: 80
    keys:
      - name: rekor.pub
      - name: ctfe.pub
      - name: fulcio_v1.crt.pem
{{- end }}
