---
{{- $ghSecretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-github-integration") | default dict -}}
{{- $secretData := (get $ghSecretObj "data") | default dict -}}
{{- if $secretData }}
apiVersion: v1
kind: Secret
metadata:
  namespace: openshift-pipelines
  name: pipelines-as-code-secret
type: Opaque
data:
  github-application-id: {{ get $secretData "ID" }}
  github-private-key: {{ get $secretData "PEM" }}
  webhook.secret: {{ get $secretData "WebhookSecret" }}
{{- end }}