{{- range $k, $v := include "infrastructure.minIOTentants.enabled" . | fromYaml }}
  {{- $secretObj := (lookup "v1" "Secret" $v.namespace $v.rootSecretName) | default dict -}}
  {{- $secretData := (get $secretObj "data") | default dict -}}
  {{- $username := (get $secretData "username") | default "minio" }}
  {{- $password := (get $secretData "password") | default (randAlphaNum 16) }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $v.namespace }}
  name: {{ $v.rootSecretName}} 
type: Opaque
data:
  username: {{ $username | b64enc }}
  password: {{ $password | b64enc }}
stringData:
  config.env: |-
    export MINIO_ROOT_USER="{{ $username }}"
    export MINIO_ROOT_PASSWORD="{{ $password }}"
{{- end }}
