{{- range $k, $v := include "infrastructure.minIOTentants.enabled" . | fromYaml }}
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
  labels:
    app: minio
  namespace: {{ $v.namespace }}
  name: {{ $k }}
spec:
  serviceAccountName: minio-tenant
  configuration:
    name: {{ $v.rootSecretName }}
  credSecret:
    name: {{ $v.storageUserSecretName }}
  # TODO: expose this configuration to "values.yaml".
  buckets:
    - name: bombastic
    - name: vexination
    - name: v11y
  pools:
    # TODO: move this section to "values.yaml".
    - name: pool-0
      servers: 1
      containerSecurityContext:
        runAsNonRoot: true
      volumesPerServer: 1
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        metadata:
          name: {{ $k }}-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
  mountPath: /export
  {{ with $v.service }}
  serviceMetadata:
    {{ with .annotations }}
    minioServiceAnnotations:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
  {{- end }}
  requestAutoCert: false
{{- end }}
