{{- $integration := (default dict .Values.backingServices.integration) -}}
{{- $data := (default dict $integration.acs) }}
{{- if $data }}
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: rhtap-acs-integration
stringData:
  endpoint: {{ $data.endpoint }}
  token: {{ $data.token }}
{{- end }}