{{- $integration := (default dict .Values.backingServices.integration) -}}
{{- $data := (default dict $integration.gitlab) -}}
{{- if $data }}
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: rhtap-gitlab-integration
stringData:
  token: {{ $data.token }}
{{- end }}