{{- $integration := (default dict .Values.backingServices.integration) -}}
{{- $data := (default dict $integration.quay) -}}
{{- if $data }}
---
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: rhtap-quay-integration
stringData:
{{- if $data.dockerconfigjson }}
  dockerconfigjson: |
{{ $data.dockerconfigjson | toJson | indent 4 }}
{{- end }}
{{- if $data.token }}
  token: {{ $data.token }}
{{- end }}
{{- end -}}