{{- $dockerconfigjson := dict }}
{{- $namespace := .Release.Namespace }}
{{- range (tuple "artifactory" "nexus" "quay") }}
  {{- $secretName := printf "rhtap-%s-integration" . }}
#
# secretName: {{ $secretName }}
  {{- $secretObj := (lookup "v1" "Secret" $namespace $secretName) | default dict }}
# secretObj: {{ $secretObj | toJson }}
  {{- $secretData := (get $secretObj "data") | default dict }}
# secretData: {{ $secretData | toJson }}
  {{- $secretContent := (get $secretData ".dockerconfigjson" | b64dec ) | default "{}" | fromJson }}
# secretContent: {{ $secretContent | toJson }}
  {{- merge $dockerconfigjson $secretContent }}
# dockerconfigjson: {{ $dockerconfigjson | toJson }}
#
{{- end }}
{{- if not $dockerconfigjson }}
  {{- required "" (printf "Did not find any image repository integrations in %s" $namespace) }}
{{- end }}
{{- range .Values.appNamespaces.namespace_prefixes }}
  {{- $namespace := . }}
  {{- range tuple "ci" "development" "prod" "stage" }}
---
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: rhtap-image-registry-auth
  namespace: {{ $namespace }}-{{ . }}
stringData:
  .dockerconfigjson: '{{ $dockerconfigjson | toJson }}'
  {{- end }}
{{- end }}
