{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-acs-integration") -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- if $secretData -}}
{{- range tuple "development" "prod" "stage" }}
---
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: rox-api-token
  namespace: rhtap-app-{{ . }}
data:
  token: {{ $secretData.token }}
  endpoint: {{ $secretData.endpoint }}
{{- end }}
{{- end }}