{{ $sa := "rhtap-installer"}}
{{- if not (lookup "v1" "ServiceAccount" .Release.Namespace $sa) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa }}
  namespace: {{ .Release.Namespace }}
{{- end }}

{{ $saAdmin := printf "%s-admin" $sa }}
{{- if not (lookup
      "rbac.authorization.k8s.io/v1"
      "ClusterRoleBinding"
      ""
      $saAdmin)
}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $saAdmin }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ $sa }}
    namespace: {{ .Release.Namespace }}
{{- end }}
