---
apiVersion: v2
name: rhtap-tpa
description: RHTAP Trusted Profile Analyzer
type: application
version: 1.5.0
appVersion: "1.3.0"

dependencies:
  - name: redhat-trusted-profile-analyzer
    version: 0.3.0
    condition: trustedProfileAnalyzer.enabled
