---
trustification:
  appDomain: __OVERWRITE_ME__
  replicas: 1
  rust:
    logFilter: debug
    backtrace: true
  openshift:
    useServiceCa: false
  ingress:
    className: openshift-default
  guac:
    database:
      sslMode: disable
      name:
        valueFrom:
          secretKeyRef:
            name: __OVERWRITE_ME__
            key: dbname
      host:
        valueFrom:
          secretKeyRef:
            name: __OVERWRITE_ME__
            key: host
      port:
        valueFrom:
          secretKeyRef:
            name: __OVERWRITE_ME__
            key: port
      username:
        valueFrom:
          secretKeyRef:
            name: __OVERWRITE_ME__
            key: user
      password:
        valueFrom:
          secretKeyRef:
            name: __OVERWRITE_ME__
            key: password
    initDatabase:    
      sslMode: disable
      name:
        valueFrom:
          secretKeyRef:
            name: __OVERWRITE_ME__
            key: dbname
      host:
        valueFrom:
          secretKeyRef:
            name: __OVERWRITE_ME__
            key: host
      port:
        valueFrom:
          secretKeyRef:
            name: __OVERWRITE_ME__
            key: port
      username:
        valueFrom:
          secretKeyRef:
            name: __OVERWRITE_ME__
            key: user
      password:
        valueFrom:
          secretKeyRef:
            name: __OVERWRITE_ME__
            key: password
  storage:
    endpoint: __OVERWRITE_ME__
    accessKey:
      valueFrom:
        secretKeyRef:
          name: __OVERWRITE_ME__
          key: username
    secretKey:
      valueFrom:
        secretKeyRef:
          name: __OVERWRITE_ME__
          key: password
  eventBus:
    type: kafka
    bootstrapServers: tpa-kafka-bootstrap
    config:
      mechanism: SCRAM-SHA-512
      securityProtocol: SASL_PLAINTEXT
      username: __OVERWRITE_ME__
      password:
        valueFrom:
          secretKeyRef:
            name: __OVERWRITE_ME__
            key: password
  oidc:
    issuerUrl: __OVERWRITE_ME__
    clients:
      # TODO: Create a dynamic secret to generate the following attributes.
      walker:
        clientSecret:
          value: 5460cc91-4e20-4edd-881c-b15b169f8a79
      #
      # TODO: DISABLE TESTING!!
      #
      testingUser:
        clientSecret:
          value: 0e6bf990-43b4-4efb-95d7-b24f2b94a525
      testingManager:
        clientSecret:
          value: ca48053c-3b82-4650-a98d-4cace7f2d567
  modules:
    bombasticWalker:
      sources:
        redhat:
          url: https://access.redhat.com/security/data/sbom/beta/
          signingKeyUrl: https://access.redhat.com/security/data/97f5eac4.txt#77E79ABE93673533ED09EBE2DCE3823597F5EAC4
          acceptV3Signatures: true
          fixLicenses: true
          job:
            schedule: "0 * * * *"
    vexinationWalker:
      sources:
        redhat:
          url: https://www.redhat.com/.well-known/csaf/provider-metadata.json
          acceptV3Signatures: true
          ignoreDistributions:
            - https://access.redhat.com/security/data/csaf/v2/advisories/
          job:
            schedule: "0 * * * *"
